query post($slug: String!) {
  post: Post(slug: $slug) {
    id,
    title,
    slug,
    content,
    tags,
    description,
    authors {
      id,
      name,
      avatar {
        id,
        handle,
        url
      }
    }
  }
}
